version: '3.8'

services:
  # ============================================================================
  # NGINX WEB SERVER
  # ============================================================================
  nginx:
    image: nginx:alpine
    container_name: gtm_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/gtmall/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - gtm_network
    labels:
      - "traefik.enable=false"

  # ============================================================================
  # API SERVER
  # ============================================================================
  api:
    build: ./api
    container_name: gtm_api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gtm
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - ENVIRONMENT=production
      - DOMAIN=gtm.baby
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - gtm_network
    labels:
      - "traefik.enable=false"

  # ============================================================================
  # POSTGRES DATABASE
  # ============================================================================
  postgres:
    image: postgres:15-alpine
    container_name: gtm_postgres
    environment:
      - POSTGRES_DB=gtm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - gtm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gtm"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================================================
  # REDIS CACHE
  # ============================================================================
  redis:
    image: redis:7-alpine
    container_name: gtm_redis
    restart: unless-stopped
    networks:
      - gtm_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  gtm_network:
    driver: bridge

volumes:
  postgres_data: 