name: gtm_app
description: GTM Flutter Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  slide_to_act: ^2.0.0
  url_launcher: ^6.2.1
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/artists/
    - assets/fonts/
    - assets/.env
    - .env
  
  fonts:
    - family: Lepka
      fonts:
        - asset: assets/fonts/Lepka.otf
    - family: NauryzKeds
      fonts:
        - asset: assets/fonts/NauryzKeds.ttf 