# Generated by Django 5.2.4 on 2025-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='Галерея товара'),
        ),
    ]
